### ISSUE TITLE
can't find executable

### ISSUE THREAD

**Issue by merkleID** [0xrawsec/kunai#18]
after a successful build, I can't find the executable 

root@deb12:~/kunai# pwd
/root/kunai
root@deb12:~/kunai# find . -iname "kunai*" -type f
root@deb12:~/kunai#

**Comment by qjerome** [comment]
strange ! If the build was successful the binary must be somewhere. Did you try running find on `/` ?

**Comment by merkleID** [comment]
yes I did, no signs of kunai bin.
I'll rebuild and see what happens

**Comment by merkleID** [comment]
into target directory there were many files and dire but not kunai
I deleted /root/kunai, re-pulled and building again.
Let's see what happens.

**Comment by merkleID** [comment]
completely rebuilt from scratch, this time kunai bin was included.
Still don't know what happened the first time.
thanks.
